name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure CMake
        run: cmake -S cmake_external_project -B cmake_external_project/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build cmake_external_project/build

      - name: Run
        run: ./cmake_external_project/build/{{ cookiecutter.__game_name_camel }}/{{ cookiecutter.game_slug }}
